#!/bin/bash

# cd ~/dev/glsdsp-samebatch-supplychain/trunk/

export ROOT_DIR=.
export CLASS_DIR=$ROOT_DIR/out
export CLASSPATH=$CLASS_DIR
export SRC="./src/*.java ./src/graph/*.java ./src/solver/*.java"

echo javac -Xlint -nowarn -d $CLASS_DIR $SRC
javac -Xlint -nowarn -d $CLASS_DIR $SRC

echo FIN DU SCRIPT

exit

